language: node_js
node_js:
  - "4"
  - "5"
services:
  - mongodb
before_install:
  - cp ./server/configs/config.sample.js ./server/configs/config.js
install:
  - npm install
script:
  - npm run build
  - npm run db
  - npm run travis



