language: node_js
node_js:
  - "6"
services:
  - mongodb
  - redis-server
before_install:
  - cp server/configs/config.sample.js server/configs/config.js
install:
  - npm i
before_script:
  - npm run manual tools/db-category
  - npm run manual tools/setup
script:
  - npm run travis
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise
    packages:
      - g++-4.8
      - mongodb-org-server
env:
  matrix:
    - CXX=g++-4.8
  global:
    - NPM_CONFIG_PROGRESS=false
    - NODE_ENV=test

